---
distrib_time_client_config: '{% if not "jails" in ansible_virtualization_tech_guest %}/etc/ntp.conf{% endif %}'
distrib_time_client_service: '{% if not "jails" in ansible_virtualization_tech_guest %}ntpd{% endif %}'
