galaxy_info:
  author: Geoffroy Desvernay
  description: wordpress install
  company: Ecole Centrale de Marseille

  license: BSD-3-Clause

  min_ansible_version: 2.8

  platforms:
  - name: FreeBSD
    versions: 
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags: []

dependencies:
  - criecm.nginx
  - criecm.php_fpm
  
