---
- name: install dhcpd
  pkgng:
    name: isc-dhcp43-server
    state: present

- block:
  - name: config dhcpd chroot
    lineinfile:
      line: '{{ dhcpdrc.line }}'
      regexp: '{{ dhcpdrc.regexp }}'
      dest: /etc/rc.conf
    with_items:
      - { line: 'dhcpd_chroot_enable="YES"', regexp: '^dhcpd_chroot_enable' }
    loop_control:
      loop_var: dhcpdrc
  - name: mkdir chroot dirs
    file:
      dest: '{{ dhcpddir }}'
      state: directory
      owner: '{{ dhcpd_user }}'
    with_items:
      - '{{ dhcpd_chrootdir }}'
      - '{{ dhcpd_includesdir }}'
    loop_control:
      loop_var: dhcpddir
  when: 'dhcpd_chroot'

- block:
  - name: syslog dhcpd socket
    lineinfile:
      line: '{{ syslogdhcpdline.line }}'
      regexp: '{{ syslogdhcpdline.regexp }}'
      dest: /etc/rc.conf
    with_items:
      - { line: 'dhcpd_chrootdir="{{ dhcpd_chrootdir }}"', regexp: '^dhcpd_chrootdir=' }
      - { line: 'altlog_proglist="dhcpd"', regexp: '^altlog_proglist=' }
    loop_control:
      loop_var: syslogdhcpdline
  - name: syslog dhcpd
    lineinfile:
      line: 'local7.*   @{{ syslog_server }}'
      insertafter: '\*\.\*.*@'
  - name: newsyslog config
    file:
      src: newsyslog_dhcpd.conf
      dest: /usr/local/etc/newsyslog.conf.d/dhcpd
      mode: '0644'
  when: 'dhcpd_chroot and syslog_server'

#- name: dhcpd rc
#  template:
#    src: dhcpd_rc.j2
#    dest: '/etc/rc.conf.d/{{ dhcpd_service_name }}'
#    owner: root
#    mode: '0644'
#    force: no
#  when: 'dhcpd_enabled'
#  tags: pkg, dhcpd
