---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - 'vars/{{ ansible_os_family }}.yml'
      skip: true
  tags: dhcpd

- include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - 'tasks/{{ ansible_os_family }}.yml'
      skip: true
  tags: dhcpd

- name: enable dhcpd
  service:
    name: '{{ dhcpd_service_name }}'
    enabled: yes
  when: 'dhcpd_enabled'
  tags: rc, dhcpd

- name: default dhcpd.local.conf
  template:
    dest: '{{ dhcpd_includesdir }}/dhcpd.local.conf'
    src: dhcpd.local.conf.j2
    mode: '0640'
    owner: root
    group: dhcpd
    force: no
  tags: config, dhcpd

- name: dir conf.d
  file:
    dest: '{{ dhcpd_configdir }}/dhcpd.conf.d'
    state: directory
    mode: '0750'
    owner: root
    group: dhcpd
  tags: dhcpd, config

- name: config dhcpd.conf
  template:
    src: dhcpd.conf.j2
    dest: '{{ dhcpd_configdir }}/dhcpd.conf'
    mode: '0750'
    owner: root
    group: dhcpd
    force: no
  tags: dhcpd, config
  notify: restart dhcpd
