---

- name: install java & tomcat
  apt:
    name:
      - tomcat8
      - '{{ debian_jdk_pkg }}'
      - libtcnative-1
    state: present
  when: do_sys

- name: install memcached
  apt:
    name: memcached
    state: present
  when: memcached_nodes is search(ansible_hostname) or memcached_nodes is search("localhost")

- name: tomcat group
  group:
    name: '{{ tomcat_group }}'
    state: present
  when: do_sys

- name: tomcat user
  user:
    name: '{{ tomcat_user }}'
    group: '{{ tomcat_group }}'
    home: /nonexistent
    shell: /usr/sbin/nologin
    createhome: False
    login_class: daemon
    state: present
  when: do_sys

- name: mkdir
  file:
    path: '{{ tomcat_log_dir }}'
    state: directory
    group: '{{ tomcat_group }}'
    mode: '0770'

- name: chown :tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rX,o-rwx
    group: '{{ tomcat_group }}'
    recurse: yes
  with_items:
    - '{{ tomcat_config_dir }}'

- name: chown tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rwX,o-rwx
    owner: '{{ tomcat_user }}'
    recurse: yes
  with_items:
    - '{{ tomcat_log_dir }}'
    - '{{ tomcat_webapps_dir }}'

- name: tomcat defaults vars
  lineinfile:
      dest: /etc/default/tomcat8
      line: '{{ item.key }}="{{ item.value }}"'
      regexp: '^{{ item.key }}='
  with_dict:
      TOMCAT8_USER: '{{ tomcat_user }}'
      TOMCAT8_GROUP: '{{ tomcat_group }}'
      JAVA_HOME: '{{ tomcat_jre_dir }}'
      JAVA_OPTS: "{{ tomcat_java_opts }} -Duser.timezone=Europe/Paris -Duser.country=fr -Duser.language=fr {% if tomcat_keystore != '' %}-Djavax.net.ssl.trustStore=/etc/ssl/{{ tomcat_keystore | regex_replace('.*/','') }} -Djavax.net.ssl.trustStorePassword='{{ tomcat_storepass }}'{% endif %}{% if classpath_adds != '' %} -cp {{ classpath_adds }}{% endif %}"
      JVM_TMP: '{% if tomcat_tmp_dir != "" %}{{ tomcat_tmp_dir }}{% else %}/var/tmp/{{ tomcat_service }}{% endif %}'
  when: do_sys
