---

- name: install java & tomcat
  pkgng:
    name: '{{ item }}'
    state: present
  with_items:
    - tomcat8
    - '{{ freebsd_jdk_pkg }}'
    - tomcat-native

- name: tomcat group
  group:
    name: '{{ tomcat_group }}'
    state: present

- name: tomcat user
  user:
    name: '{{ tomcat_user }}'
    group: '{{ tomcat_group }}'
    home: /nonexistent
    shell: /usr/sbin/nologin
    createhome: False
    login_class: daemon
    state: present

- name: mkdir
  file:
    path: '{{ tomcat_log_dir }}'
    state: directory
    group: '{{ tomcat_group }}'
    mode: '0770'

- name: chown :tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rX,o-rwx
    group: '{{ tomcat_group }}'
    recurse: no
  with_items:
    - '{{ tomcat_config_dir }}'

- name: chown tomcat dirs
  file:
    path: '{{ item }}'
    mode: u=rwX,g=rwX,o-rwx
    owner: '{{ tomcat_user }}'
    recurse: yes
  with_items:
    - '{{ tomcat_log_dir }}'
    - '{{ tomcat_webapps_dir }}'
    - '{{ tomcat_work_dir }}'
    - '{{ tomcat_config_dir }}/Catalina'

- name: login.conf utf8
  blockinfile:
    block: |
      tomcat:\
            :charset=UTF-8:\
            :lang=en_US.UTF-8:\
            :tc=default:
    marker: '{mark} ANSIBLE MANAGED tomcat'
    backup: yes
    validate: 'cap_mkdb %s'
    notify: cap_mkdb login.conf

- name: newsyslog
  template:
    src: newsyslog_tomcat.conf
    dest: /usr/local/etc/newsyslog.conf.d/tomcat.conf

- name: enable tomcat
  lineinfile:
      dest: /etc/rc.conf
      line: '{{ item.key }}="{{ item.value }}"'
      regexp: '^{{ item.key }}='
  with_dict:
      tomcat8_enable: YES
      tomcat8_catalina_user: '{{ tomcat_user }}'
      tomcat8_stdout: '{{ tomcat_log_dir }}/catalina.out'
      tomcat8_stderr: '{{ tomcat_log_dir }}/catalina.err'
      tomcat8_java_opts: "{{ tomcat_java_opts }}{% if tomcat_keystore != '' %} -Djavax.net.ssl.trustStore=/etc/ssl/{{ tomcat_keystore | regex_replace('.*/','') }} -Djavax.net.ssl.trustStorePassword='{{ tomcat_storepass }}'{% endif %}"
      tomcat8_java_home: '{{ tomcat_jre_dir }}'
      tomcat8_classpath: "{% if classpath_adds != '' %}:{{ classpath_adds }}{% endif %}"
      tomcat8_tmp_dir: "{% if tomcat_tmp_dir != '' %}{{ tomcat_tmp_dir }}{% else %}/var/tmp/{{ tomcat_service }}{% endif %}"
      tomcat8_wait: '5'
