---
# deploy one webapp
- include_vars: webapp.yml

- name: copy git dir
  git:
    depth: 1
    dest: '{{ webapp.gitdst }}'
    repo: '{{ webapp.gitsrc }}'
  when: '"gitsrc" in onewebapp and "gitdst" in onewebapp'

- name: chown git dest
  file:
    state: directory
    user: root
    group: '{{ tomcat_group }}'
    mode: g+r,o-rwx
    recursive: yes
  when: '"gitdst" in onewebapp'

- name: delete old war
  file:
    path: '{{ tomcat_webapps_dir }}/{{ webapp.war }}'
    state: absent
  when: '"war" in onewebapp'

- name: delete tomcat cache
  file:
    path: '{{ tomcat_work_dir }}/Cataline/{{ onewebapp.key }}'
    state: absent
    recurse: yes

# task for each webapp
- name: install war file
  copy:
    src: '{{ webapp.war }}'
    dest: '{{ tomcat_webapps_dir }}'
    group: '{{ tomcat_group }}'
    mode: '0640'
  when: '"war" in onewebapp'

- name: webapp script
  command: '{{ webapp.gitdst }}/{{ webapp.script }}'
  when: '"script" in onewebapp'
