#SPDX-License-Identifier: MIT-0
---
# handlers file for criecm.time
- name: restart time_client
  service:
    name: '{{ time_client.service }}'
    state: restarted
  when: not start_time_client.changed
