#SPDX-License-Identifier: MIT-0
---
# handlers file for criecm.time
- name: restart time_client
  service:
    name: '{{ time_client_service }}'
    state: restarted
  when: time_client_service | default(False) and not start_time_client.changed | default(False)
