---
galaxy_info:
  author: Geoffroy Desvernay
  description: tomcat and webapps
  company: Ecole Centrale Marseille

  license: BSD

  min_ansible_version: 2.9

  platforms:
    - name: FreeBSD
      versions:
        - all
    - name: Debian
      versions:
        - bullseye
        - trixie

  galaxy_tags:
    - tomcat

dependencies:
  - role: criecm.x509

