---
- name: restart apache
  service:
    name: '{{ apache_service }}'
    state: '{{ apachestate }}'
  with_items:
    - stopped
    - started
  loop_control:
    loop_var: apachestate
  register: apacherestarted
  when: not apachestarted.changed | default(False)
  throttle: 1

- name: reload apache
  service:
    name: '{{ apache_service }}'
    state: reloaded
  when: not apachestarted.changed | default(False) and not apacherestarted.changed | default(False)
  throttle: 1
