#SPDX-License-Identifier: MIT-0
---
# defaults file for criecm.sysutils
# path prefix for relative gits[path]'s
gits_root: /root
 
# gits: git repos to deploy in /usr/local/admin/sysutils
gits: []
# idem, added to gits at runtime (for use in host vars or ...)
host_gits: []
# idem, for use in roles
role_gits: []
# and in group_vars :)
group_gits: []

# ssh key for above git repos (fiole name in files/, copied to /root/.ssh/)
git_ssh_key:
