---
has_ipv6: '{% if ansible_all_ipv6_addresses | ansible.utils.ipaddr("2000::/3") | count() > 0 %}True{% else %}False{% endif %}'
has_ipv6_only: '{% if ansible_all_ipv6_addresses | ansible.utils.ipaddr("2000::/3") | count() > 0 and ansible_all_ipv4_addresses | count == 0 %}True{% else %}False{% endif %}'
